CPP = g++
CFLAGS = -std=c++20 -Wall

# Pattern rule for compiling source files
%.exe: %.cpp
	$(CPP) $< $(CFLAGS) -o $@
	./$@

# Targets for each exercise
ex1: Ex1.exe
ex2: Ex2.exe
ex3: Ex3.exe
ex4: Ex4.exe
ex5: Ex5.exe
ex6: Ex6.exe
ex7: Ex7.exe
ex8: Ex8.exe
ex9_10: Ex9_10.exe
ex17: Ex17.exe
ex18_19_20: Ex18_19_20.exe