CPP = g++
CFLAGS = -std=c++20 -Wall

# Pattern rule for compiling source files
%.exe: %.cpp
	$(CPP) $< $(CFLAGS) -o $@
	./$@

# Targets for each exercise
ex1: Ex1.exe
ex2: Ex2.exe
ex3: Ex3.exe
ex4_5: Ex4_5.exe
ex6_7: Ex6_7.exe